block.10000=minecraft:short_grass minecraft:tall_grass minecraft:fern minecraft:large_fern
block.10001=minecraft:wheat minecraft:carrots minecraft:potatoes

block.8=minecraft:water
block.9=minecraft:flowing_water

block.20=minecraft:glass
block.95=minecraft:stained_glass
block.160=minecraft:stained_glass_pane

block.41=minecraft:gold_block
block.42=minecraft:iron_block
block.57=minecraft:diamond_block
block.133=minecraft:emerald_block

block.50=minecraft:torch minecraft:wall_torch minecraft:glowstone minecraft:lava minecraft:flowing_lava minecraft:lantern minecraft:sea_lantern minecraft:magma_block minecraft:campfire minecraft:soul_torch minecraft:soul_wall_torch minecraft:soul_campfire minecraft:soul_lantern minecraft:shroomlight minecraft:redstone_lamp
block.60=minecraft:iron_block minecraft:gold_block minecraft:diamond_block minecraft:emerald_block minecraft:netherite_block minecraft:lapis_block minecraft:copper_block minecraft:exposed_copper minecraft:weathered_copper minecraft:oxidized_copper minecraft:cut_copper minecraft:exposed_cut_copper minecraft:weathered_cut_copper minecraft:oxidized_cut_copper